import { taskName } from '@cinerino/factory';

import { IAttributes as ISendOrderActionAttributes } from '../action/transfer/send/order';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';

export type IData = ISendOrderActionAttributes;
export interface IAttributes extends TaskFactory.IAttributes {
    name: taskName.SendOrder;
    data: IData;
}
/**
 * 注文配送タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
