import { taskName } from '@cinerino/factory';

import { IAttributes as IUnRegisterProgramMembershipActionAttributes } from '../action/interact/unRegister/programMembership';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';

export type IData = IUnRegisterProgramMembershipActionAttributes;
export interface IAttributes extends TaskFactory.IAttributes {
    name: taskName.UnRegisterProgramMembership;
    data: IData;
}
/**
 * 会員プログラム登録解除タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
