import { taskName, taskStatus } from '@cinerino/factory';

import { IExtendId } from './autoGenerated';
import SortType from './sortType';

export type IData = any;

/**
 * タスク実行結果インターフェース
 */
export interface IExecutionResult {
    executedAt: Date;
    error: any;
}

/**
 * タスク属性インターフェース
 */
export interface IAttributes {
    /**
     * タスク名
     */
    name: taskName;
    /**
     * タスク状況
     */
    status: taskStatus;
    /**
     * いつ実行するか
     */
    runsAt: Date;
    /**
     * あと何回トライできるか
     */
    remainingNumberOfTries: number;
    /**
     * 最終トライ日時
     */
    lastTriedAt?: Date;
    /**
     * すでにトライした回数
     */
    numberOfTried: number;
    /**
     * 実行結果リスト
     */
    executionResults: IExecutionResult[];
    /**
     * データ
     * TaskNameによってインターフェースが決定する
     */
    data: IData;
}

/**
 * タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;

/**
 * ソート条件インターフェース
 */
export interface ISortOrder {
    runsAt?: SortType;
    lastTriedAt?: SortType;
    numberOfTried?: SortType;
}

/**
 * 注文検索条件インターフェース
 */
export interface ISearchConditions<T extends taskName | string> {
    limit?: number;
    page?: number;
    sort?: ISortOrder;
    name?: T;
    statuses?: taskStatus[];
    runsFrom?: Date;
    runsThrough?: Date;
    lastTriedFrom?: Date;
    lastTriedThrough?: Date;
}
