version: 2
jobs:
  build:
    working_directory: ~/project
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: node version
          command: node -v
      - run:
          name: npm version
          command: npm -v
      # - run:
      #     name: Update npm
      #     command: 'sudo npm install -g npm@latest'
      - run:
          name: configure npm for private modules
          command: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install npm packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: compile typescript
          command: npm run build
  test:
    working_directory: ~/project
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: run npm test
          command: npm test
      # - run:
      #     name: Generate code coverage
      #     command: './node_modules/.bin/nyc report --reporter=text-lcov'
      # - store_artifacts:
      #     path: test-results.xml
      #     prefix: tests
      # - store_artifacts:
      #     path: coverage
      #     prefix: coverage

# Used for orchestrating all jobs.
workflows:
  version: 2

  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          # filters:
          #   branches:
          #     only: master