dependencies:
  pre:
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

version: 2
jobs:
  build:
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: echo NPM_TOKEN
          command: printenv NPM_TOKEN
      - run:
          name: npm config set
          command: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      - run:
          name: echo node version
          command: node -v
      - run:
          name: echo npm version
          command: npm -v
      # - run:
      #     name: Update npm
      #     command: 'sudo npm install -g npm@latest'
      - run:
          name: Install npm packages
          command: npm install
      - run:
          name: compile typescript files
          command: npm run build
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Test
          command: npm test
      # - run:
      #     name: Generate code coverage
      #     command: './node_modules/.bin/nyc report --reporter=text-lcov'
      # - store_artifacts:
      #     path: test-results.xml
      #     prefix: tests
      # - store_artifacts:
      #     path: coverage
      #     prefix: coverage

# Used for orchestrating all jobs.
workflows:
  version: 2

  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master